In [ ]:
#input

#integer
a=int(input("enter the number") )

#decimal pr float
#b=float(input("enter the number"))

#character or string
#c=input("enter your name")

In [ ]:
# sum of two numbers by using input
a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print("the sume is ",c)





In [ ]:
# simple interest 
p=int(input("enter the principle"))
r=float(input("enter the rate"))
t=int(input("enter the time"))
si=p*r*t/100
print("the interest is",si)






      
      

In [ ]:
# average
a=float(input("enter the number"))
b=float(input("enter the number"))
c=float(input("enter the number"))
avg=(a+b+c)/3
print ("the average is ",avg)



In [ ]:
p=float(input("enter the marks"))
c=float(input("enter the marks"))
m=float(input("enter the marks"))
e=float(input("enter the marks"))
h=float(input("enter the marks"))
s=p+c+m+e+h
per=s*100/500
print("the percentage is ",per)



In [ ]:
a=90
b=13
print("the sum is ",a+b)
print("the sub is ",a-b)
print("the pro is ",a*b)
print("the div is ",a/b)
print("the mod is ",a%b)
print("the floar div is ",a//b)
print("the exponent is ",a**b)


In [ ]:
p=65
c=98
m=78
e=78
h=56
s=p+c+m+e+h
per=s*100/500
print("the percentage is ",per)

In [ ]:
import math
n=10
x= math
print(x)
3.16227


In [ ]:
associativity of operators
p=paronthysis
e=exponent
h=multiply
d=divide
a=addition
s=sub

In [ ]:
#swapping of two numbers 
a=100
b=200
print("before swapping")
print("a",a)
print("b",b)


In [ ]:
#sum of two numbers by using input 
a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print("the sum is",c)

In [ ]:
#simple interest 
p=int(input("enter the principle"))
r=float(input("enter the rate"))
t=int(input("enter the time"))
si=p*r*t/100
print("the interest is",si)

In [ ]:
#average
a=float(input("enter the number"))
b=float(input("enter the number"))
c=float(input("enter the number"))
avg=(a+b+c)/3
print("the average is",avg)

In [ ]:
p=float(input("enter the marks"))
c=float(input("enter the marks"))
m=float(input("enter the marks"))
e=float(input("enter the marks"))
h=float(input("enter the marks"))
s=p+c+m+e+h
per=s*100/500 
print("sum is",s)
print("the percentage is",per)

In [ ]:
#import math
n=int(input("enter the number"))
x=math
print(x)

In [ ]:
# variable---- variable is a container that store value or values
# it can be change when the operations are performed on it


In [ ]:
# some rules to create variable

# variable name can not start with a digit 

In [ ]:
1a=10 #wrong


In [ ]:
# there is no space are allowed in varable name

#student name ="madrid"

In [ ]:
#instead of space we can use "_"
student_name"madrid"

In [ ]:
_a=10

In [ ]:
_a_=10

In [ ]:
#python is case sensitive

a=10
A=10

both have different values 

In [ ]:
# automatic memory allocation 

a=10
id(a)

In [ ]:
# keywords are never used as an variable name 
# they are knowns as "reserved" keywords


In [ ]:
False     def        if        raise 
None      del        import    return
True      elif       in        try 
and       else       is        while
as        except     lambda    with 
assert    finally    nonlocal  yield 
break     for        not 
class     from       or 
continue  global     pass
await     async      


In [ ]:
# opertors 


#Arithmetic 
#comparision 
#Assignment 
#logical operator
#Bitwise





In [ ]:
#Arithmetic
# + - / // % **

In [ ]:
a=100
b=23


In [ ]:
a+b

In [ ]:
a-b

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
a%b  # return remainder

In [ ]:
a//b  #floor division

In [ ]:
a=45
b=2

In [ ]:
a**b   # a to the power b

In [ ]:
#output function

#print()

#Msg

print("hello")

# for value of the variable 
a=12
print(a)




In [ ]:
# Msg with value 

b=100
print("the value is",b)

In [ ]:
# declaration 

# Logic

# output

In [ ]:
# sum of two numbers 

a=200
b=500
c=a+b
print("the sume is",c)

In [ ]:
# simple intrest 
p=3000
r=5.6
t=3
si=p*r*t/100
print("the interest is",si)

In [ ]:
# average 
a=300
b=400
c=700
avg=(a+b+c)/3
print("the average is",avg)

In [ ]:
#p--- paranthysis 
#E--- Exponent
#M--- Multiplication
#D--- Division 
#A--- Addition
#S--- Substraction


In [ ]:
# calculater percentage
p=57
c=98
m=56
e=89
h=98
s=p+c+m+e+h
per=s*100/500
print("the sum is",si)
print("the percentage is",per)

In [ ]:
# input--- runtime values

# integer--- int(input("enter the number"))

# decimal---- float(input("enter the number"))

# string or character--- input("msg")

these are data types

In [ ]:
a=10
type(a)

In [ ]:
x=12.34
type(x)

In [ ]:
y="vansh"
type(y)

In [ ]:
a=[12,23,34,44,45]
type(a)

In [ ]:
b=(12,23,34,45)
type(b)

In [ ]:
c={12,23,34,45}
type(c)

In [ ]:
d={"Name":"Sahil","Age":30}
type(d)

In [ ]:
# sum of two numbers 
a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print("the value is",c)

In [ ]:
p=int(input("enter the value of the principle"))
r=float(input("enter the rate"))
t=int(input("enter the time"))
si=p*r*t/100
print("the simple interest is",si)

In [ ]:
a=float(input("enter the number"))
b=float(input("enter the number"))
c=float(input("enter the number"))
avg=(a+b+c)/3
print("the average is",avg)

In [ ]:
mark1=int(input("enter the physic marks"))
mark2=int(input("enter the chemistry marks"))
mark3=int(input("enter the maths marks"))
mark4=int(input("enter the hindi marks"))
mark5=int(input("enter the english marks"))
per=(mark1+mark2+mark3+mark4+mark5)*100/500
print("the percentage is",per)

In [ ]:
import math 

In [ ]:
n=int(input("enter the number"))
x=math.sqrt(n)
print(x)

In [ ]:
#pow(x,y)

a=int(input("enter the value of the base"))
b=int(input("enter the value of the exponent"))
x=math.pow(a,b)
print(x)


In [ ]:
# comparision operator

#==
# what is difference betwee = a ==
a=10
a==10

In [ ]:
#< less than
#> greater than
#<= less than or equal
#>= greater than or equal

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
print("a==b",a==b)
print("a<b",a<b)
print("a>b",a>b)
print("a<=b",a<=b)
print("a>=b",a>=b)

In [ ]:
p=int(input("enter then value of principle"))
r=float(input("enter the rate"))
t=int(input("enter the time"))
si=p+r+t/100
print("the simple interest",si)

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print("the sum of",c)

In [ ]:
a=float(input("enter the number"))
b=float(input("enter the number"))
c=float(input("enter the number"))
avg=(a+b+c)/3
print("the average of",avg)

In [ ]:
mark1=int(input("enter the marks of math"))
mark2=int(input("enter the marks of bio"))
mark3=int(input("enter the marks of english"))
mark4=int(input("enter the marks of hindi"))
mark5=int(input("enter the marks of chemistry"))
per=(mark1+mark2+mark3+mark4+mark5)*100/500
print("the percentage of",per)

In [ ]:
#conditional statement

# if ----- only if
# if  then else
# if elif ladder from
# nested if



In [ ]:
syntax

if condtion: statement which is only true


In [ ]:
n=int(input("enter the number"))
if n==10:
   print("you won")

In [ ]:
n=int(input("enter the number"))
if n>0:
    print("+ve number")
if n<0:
    print("--ve number")
if n==0:
    print("number is zero itself")
    


In [ ]:
n=int(input("enter the number"))
if n%2==0:
   print("even number")
else:
   print("odd number")

In [ ]:
year =int(input("enter the number"))
if year%4==0:
   print("leap year")
else:
   print("non leap year")

In [ ]:
age=int(input("enter the age"))
if age>=18:
    print("eligible to vote")
else:
    print("not eligible")

In [ ]:
# change the positive number if -ve is being entered

n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
if elif ladder form
syntax 
if condition : 
    statement
elif condition:
    statment
elif condition:
    statment
else:
    statment
    

In [ ]:
day=int(input("enter the number b/w 1--7"))
if day==1:
    print("sun")
elif day==2:
    print("mon")
elif day==3:
    print("tue")
elif day==4:
    print("wed")
elif day==5:
    print("thu")
elif day==6:
    print("fri")
elif day==7:
    print("sat")
else:
    print("invalid choice")
          
    

In [ ]:
p=float(input("enter the marks"))
c=float(input("enter the marks"))
m=float(input("enter the marks"))
e=float(input("enter the marks"))
h=float(input("enter the marks"))
s=p+c+m+e+h
per=s*100/500
print("the percentage is",per)
if per>=60:
   print("first Div")
elif per>=45:
    print("second div")
elif per>=33:
    print("third div")
else:
    print("fail")



        

In [ ]:
logical operator

and-- all of the conditions must be true for true output

or-- any of the condition must be true for true output

In [ ]:
# greatest among three numbers

a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")

In [ ]:
# check vowel or consonant 

ch=input("enter an alphabet")

if ch=='a' or ch=='e' or ch=='i' or ch=='o' or ch=='u':
    print("vowel")
if ch=='A' or ch=='E' or ch=='I' or ch=='O' or ch=='U':
    print("consonant")

In [ ]:
ch=input("enter an alphabet")
if ch in['a','e','i','o','u','A','E','I','O','U']:
    print("vowel")
else:
    print("consonant")

In [ ]:
# traffic light

ch=input("enter the alphabet as \n r for red \n g for green \n y for yellow \n")
if ch=='r' or ch=='R':
    print("stop")
elif ch=='y' or ch=='Y':
     print("get ready")
elif ch=='g' or 'G':
    print("move forward")
else:
    print("pay chalaan")

In [ ]:
# take values of length and breadth of rectangle from user and check if it is square
length = int(input("enter the length"))
breadth = int(input("enter the breadth"))
if length == breadth:
    print("yes, it is square")
    print("the area of square is", length**2)
else:
    print("no, it is only rectangle")
    print("the area of rectangle is", length*breadth)

In [ ]:


hungry = True
if hungry:
     print('Feed me!')
else:
     print('I am not hungry')

In [ ]:
loc = 'Auto shop'

if loc =='Auto shop':
    print('Cars are cool!')
elif loc == 'Bank':
    print('Money is cool!')
elif loc == 'Store':
    print('Welcome to the store!')
else:
    print('I do not know so much')

In [ ]:
p=float(input("enter the marks"))
c=float(input("enter the marks"))
m=float(input("enter the marks"))
e=float(input("enter the marks"))
h=float(input("enter the marks"))
si=p+c+m+e+h
per=si*100/500
print("the percentage is",per)
if per>=60:
    print('first div')
elif per>=45:
    print('secound div')
elif per>=30:
    print('third div')
else:
    print('fail')



In [ ]:
p=float(input("enter the marks"))
c=float(input("enter the marks"))
m=float(input("enter the marks"))
e=float(input("enter the marks"))
h=float(input("enter the marks"))
si=p+c+m+e+h
per=si*100/500
print("the percentage is",per)
if per>=60:
    print('first div')
elif per>=45:
    print('secound div')
elif per>=35:
    print('third div')
else:
    print('fail')

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")


In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")


In [ ]:
loc = 'Store'

if loc== ('Auto shop'):
    print('cars are cool')
elif loc== ('Store'):
    print('your welcome')
elif loc== ('Bank'):
    print('Money is cool')
else:
    print('I have no idea')


In [ ]:
ch=input("enter the alphabet as \n r for red \n g for green \n y for yellow \n")
if ch=='r' or ch=='R':
    print('stop')
elif ch=='g' or ch=='G':
    print('move forward')
elif ch=='y' or ch=='Y':
    print('get ready')
else:
    print('pay chalaan')

In [ ]:
ch=input("enter the alphabet as \n r for red \n g for green \n y for yellow \n")
if ch=='r' or ch=='R':
    print('stop')
elif ch=='y' or ch=='Y':
    print('get ready')
elif ch=='g' or ch=='G':
    print('get ready')
else:
    print('pay chalaan')

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")

In [ ]:
# runtime value program
# we have to input the values of the variable while execution of program 


In [ ]:
ch=input("enter the alphabet as \n 'r' for red \n 'g' for green \n y for yellow \n")
if ch=='r' or ch=='R':
    print('Stop')
elif ch=='y' or ch=='Y':
    print('Get ready')
elif ch=='g' or ch=='G':
    print('Move forward')
else:
    print("Pay chalaan")


In [ ]:
loc = 'mall'
if loc== ('mall'):
    print('shopping area')
elif loc==('store'):
    print('your welcome')
elif loc==('bank'):
    print('money is cool')
else:
    print('no idea')

In [ ]:
age=int(input("enter the age"))
if age>=18:
    print("eligible")
else:
    print("not eligible")

In [ ]:
year = int(input("enter the year"))
if year%4==0:
    print("leap year")
else:
    print("non leap year")

In [ ]:
age=int(input("enter the age"))
if age>=18:
    print("eligible for vote")
else:
    print("not eligible for vote")

In [ ]:
year=int(input("enter the year"))
if year%4==0:
    print("leap year")
else:
    print("non leap year")


In [ ]:
n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
day=int(input("enter the number b/w 1--7"))
if day==1:
    print("SUN")
elif day==2:
    print("MON")
elif day==3:
    print("TUE")
elif day==4:
    print("WED")
elif day==5:
    print("THUS")
elif day==6:
    print("FRI")
elif day==7:
    print("SAT")
else:
    print("INVALID INVOICE")

In [ ]:
a=int(input("enter the number"))
b=float(input("enter the number"))
c=int(input("enter the number"))
si=a+b+c/100
print("the number of",si)

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print("the number of",c)

In [ ]:
day=int(input("enter the day b/w 1--7"))
if day==1:
    print("Sun")
elif day==2:
    print("Mon")
elif day==3:
    print("Tue")
elif day==4:
    print("Wed")
elif day==5:
    print("Thus")
elif day==6:
    print("Fri")
elif day==7:
    print("'Sat")
else:
    print("Invalid Invoice")
        

In [ ]:
n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
n=int(input("enter the number"))
if n<0:
    print(n*(-1))
else:
    print(n)

In [ ]:
year=int(input("enter the year"))
if year%4==0:
    print("leap year")
else:
    print("non leap year")

In [ ]:
age=int(input("enter the age"))
if age>=18:
    print("eligible for vote")
else:
    print("not eligible for vote")

In [ ]:
age=int(input("enter the age"))
if age>=18:
    print("eligible for vote")
else:
    print("not eligible for vote")

In [ ]:
ch=input("enter the alphabet \n 'r' for red \n 'g' for green \n y for yellow \n")
if ch=='r' or ch=='R':
    print("stop")
elif ch=='g' or ch=='G':
    print("move forward")
elif ch=='y' or ch=='Y':
    print("get ready")
else:
    print("pay challan")

In [ ]:
ch=input("enter the alphabet \n 'r' for red \n 'g' for green \n 'y' for yellow")
if ch=='r' or ch=='R':
    print("stop")
elif ch=='y' or ch=='Y':
    print("get ready")
elif ch=='g' or ch=='G':
    print("move forward")
else:
    print("pay chalaan")

In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
if a>b and a>c:
    print(a,"is greatest")
elif b>a and b>c:
    print(b,"is greatest")
else:
    print(c,"is greatest")

In [ ]:
a=float(input("enter the marks"))
b=float(input("enter the marks"))
c=float(input("enter the marks"))
d=float(input("enter the marks"))
e=float(input("enter the marks"))
si=a+b+c+d+e
per=si*100/500
if per>=60:
    print("first div")
elif per>=45:
    print("secound div")
elif per>=30:
    print("third div")
else:
    print("fail")

In [ ]:
a=float(input("enter the marks"))
b=float(input("enter the marks"))
c=float(input("enter the marks"))
d=float(input("enter the marks"))
e=float(input("enter the marks"))
si=a+b+c+d+e
per=si*100/500
if per>60:
    print("first div")
elif per>45:
    print("secound div")
elif per>30:
    print("third div")
else:
    print("fail")

In [ ]:
if inside if----
---------------

# greatest among three numbers 

a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))

if a>b:
    if a>c:
        print(a,"is greatest")
    else:
        print(c,"is greatest")
else:
    b>c:
    print(c,"greatest")


In [ ]:
a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))

if a>b:
    if a>c:
        print(a,"is greatest")
    else:
        print(c,"is greatest")
else:
    if b>c:
        print(b,"is greatest")
    else:
        print(c,"is greatest")
    
    

In [ ]:
loop statement
--------------

# while loop --- interview
# for loop --- project

In [ ]:
print your name 10 times

In [ ]:
i=1
while i<=10:
    print("satyam")
    i=i+1

In [ ]:
print first 10 natural number

In [ ]:
i=1
while i<=10:
    print(i)
    i=i+1

In [ ]:
i=1
while i<=10:
    print(i,end=" ")
    i=i+1

In [ ]:
print the sum first 10 natural number

s=s+i
s=0+1=1
s=1+2=3
s=3+3=6
s=6+4=10



#s=45+10=55

In [ ]:
i=1
s=0
while i<=10:
    s=s+i
    i=i+1

print("the sum is",s)

In [ ]:
# print only even numbers from 1--100

In [ ]:
i=1
while i<=100:
    if i%2==0:
        print(i,end=" ")
    i=i+1

In [ ]:
i=1
while i<=100:
    if i%2==1:
        print(i,end=" ")
    i=i+1

In [ ]:
i=1
while i<=100:
    if i%0==0:
        print(i,end=" ")
    i=i+1

In [ ]:
# print the sum of even number and odd number separately from 1--100

In [ ]:
i=1
se=0
so=0
while i<=100:
    if i%2==0:
        se=se+i
    else:
        so=so+i
    i=i+1

print("the sum of even numbers",se)
print("the sum of odd numbers",so)

In [ ]:
# table of given number

In [ ]:
n=int(input("enter the number"))
i=1
while i<=10:
    print(n*i)
    i=i+1


In [ ]:
n=int(input("enter the number"))
i=1
while i<=10:
    print(n,"*",i,"=",n*i)
    i=i+1

In [ ]:
n=int(input("enter the number"))
i=1
while i<=n:
    if n%i==0:
        print(i,end=" ")
    i=i+1

In [ ]:
# factorial of a given number 

In [ ]:
n=int(input("enter the number"))
f=1
while n>0:
    f=f*n
    n=n-1

print("the fectorial is",f)
    

In [ ]:
n=int(input("enter the number"))
f=1
while n>0:
    f=f*n
    n=n-1

print("the fectorial is",f)

In [ ]:
n=int(input("enter the number"))
i=1
co=0
while i<=n:
    if n%i==0:
        co=co+1
    i=i+1

if co==2:
    print("prime number")
else:
    print("non prime number")

In [ ]:
# some of digits of a number 

# 4534---4+5+3+4=16

In [ ]:
n=int(input("enter the number"))
s=0
while n>0:
    rem=n%10
    s=s+rem
    n=n//10

print("the sum is",s)

In [ ]:
n=4534

rem=n%10
s=s+rem
n=n//10



rem=4534%10-----4
s=0+4=4
n=4534//10---453



rem=453%10---3
s=4+3=7
n=453//10----45


rem=45%10----5
s=7+5=12
n=45//10----4


rem=4%10----4
s=12+4=16
n=4//10--0


In [ ]:
# reverse of a number

In [ ]:
4534--4354

In [ ]:
n=int(input("enter the number"))
rev=0
while n>0:
    rem=n%10
    rev=rev*10+rem
    n=n//10

print("the reverse is",rev)

In [ ]:
rem=4534%10-----4
rev=rev*10+rem
n=n//10



rem=453%10---3
rev=0*10+4=4
n=4534//10----45


rem=45%10----5
rev=4*10+3=43
n=45//10----4


rem=4%10----4
rev=43*10+=4354
n=4//10--0

In [ ]:
# palindrome number 

In [ ]:
n=int(input("enter the number"))
rev=0
n1=n
while n>0:
    rem=n%10
    rev=rev*10+rem
    n=n//10

if n1==rev:
    print("palindrome number")
else:
    print("not palindrome number")

In [ ]:
# 153----1**3+5**3+3**3---153
# 1634---1**$+^**4+3**4+4**4---1634---- (Armstrong number)

In [ ]:
n=int(input("enter the number"))
s=0
n1=n

while n>0:
    rem=n%10
    s=s+rem**3
    n=n//10

if s==n1:
    print("armstrong number")
else:
    print("not armstrong")

In [ ]:
153,370,371,407

In [ ]:
# any

In [ ]:
n=int(input("enter the number"))
s=0
co=0
n1=n
n2=n
while n>0:
    rem=n%10
    co=co+1
    n=n//10

while n1>0:
     rem=n1%10
     s=s+rem**co
     n1=n1//10
if s==n2:
    print("armstrong number")
else:
    print("not armstrong number")

In [ ]:
for loop

In [ ]:
for i in "Datascince":
    print(i)
for i in [12,23,34,45,56,67]:
    print(i)
for i in (12,23,34,45,56):
    print(i)
for i in {12,23,34,45}:
    print(i)
for i in {"name":"Dev","age":30}:
    print(i)
    

In [ ]:
{" ":" "," ":12}:---- Dictnory
{ }----- Set
( )---- Touple

In [ ]:
# range

range(10)---0---9
range(1,10)---1----9
range(1,100,4)--- 1+5+9+13---

In [ ]:
for i in range (10):
    print(i,end=" ")


In [ ]:
for i in range (1,10):
    print(i,end=" ")

In [ ]:
for i in range (1,100,4):
    print(i,end=" ")

In [ ]:
for i in range (100,1,-4):
    print(i,end=" ")

In [ ]:
# print your name 10 times 

In [ ]:
for i in range (10):
    print("satyam")

In [ ]:
# print first 10 natural number

In [ ]:
for i in range(1,11):
    print(i,end=" ")

In [ ]:
for i in range(2,102,2):
    print(i,end=" ")


In [ ]:
for i in range(6,106,6):
    print(i,end=" ")

se=0
so=0
for i in range(1,101):
     if i%2==0:
     se=se+i
    else:
    sp=so+1
print("sum of the odd number",odd)
print("sum of the even numer",even)





In [ ]:
n=int(input("enter the  number"))
for i in range(1,n+1):
    if n%i==0:
        print(i,end=" ")


In [ ]:
n=int(input("enter the number"))
for i in range(1,10):
    print(i,"*",i,"=",n*i)

In [ ]:
n=int(input("enter the number"))
for i in range(1,n+1):
    if n%i==0:
        co=co+1
if co==2:
    print(n,"is prime numnber")
else:
    print(n,"is not a prime number")

In [ ]:
a=(1,2,3,4,5,6,7)

In [ ]:
for i in a:
    if i%2==0:
        print(i)
    else:
        print("bye")

In [ ]:
a="hello everyone how are you"
vowel=["a","i","e","o","u"]
for i in a:
    if i not in vowel:
        print(i)

In [ ]:
word="hello1"
for w in word:
    if w=="l":
        print("good one")

else:
    print("data scince")

In [ ]:
name="satyam"
for i in name:
    if i=="t":
        print("that's great")
    print(i)
    print("hello")

print(i)

In [ ]:
name="satyam"

for i in name:
    if i=="y":
        print("hii")
    print(i)

In [ ]:
for i in range(11,1000):
   n=i
   rev=0
   while n>0:
       rem=n%10
       rev=rev*10+rem
       n=n//10
   if rev==i:
        print(i,end=" ")

In [ ]:
for i in range(101,1000):
   n=i
   s=0
   while n>0:
       rem=n%10
       s=s+rem**3
       n=n//10
   if s==i:
        print(i,end=" ")

In [ ]:
n=int(input("enter the number"))
rev=0
while n>0:
    rem=n%10
    rev=rev*10+rem
    n=n//10

print("the reverse is",rev)
    


In [ ]:
# list 

In [ ]:
array--- collection of similar data items homogenous

sequence data structure--inserting 1,2,3,4,5,etc.
hectregenous---- Data ara availabe for more than 1,2 types
ordered or indexed--- we can access throung index
,"Mutable"----we can change after completing 
identification 
enclosed in []("square bracket)

In [ ]:
ls=[]
print[ls]

ls=[12,23,34,45,56]#list of integers
print[ls]
ls=['a','e','i','o','u']#list of chars or string
print[ls]
ls=[12,23,56,76] # list of float
print[ls]
ls=[12,23,34,65,56."hello"] # mixed type
print[ls]

 #by using list constructor

In [ ]:
ls=list("HELLO")
print(ls)

In [ ]:
ls=list((12,23,3,4))
print(ls)

In [ ]:
Accessing of list Elements  
print(ls[0])
print(ls[3])

when we move left to right index are 0--- onwards 
but if we move from right to left then index will start from -1

print(ls[-3]) #77 

In [ ]:
ls=[11,22,33,44,55,66,77,88,99]
print(ls[0])
print(ls[3])
print(ls[-3])

In [ ]:
# Accessing in nested list

In [ ]:
ls=[12,23,34,45,[67,78,89,98,[98,867,76]],56,[87]]
print(ls[3])
print(ls[4])
print(ls[4][3])
print(ls[4][4])
print(ls[4][4][1])

In [ ]:
ls=[12,34,78,43,[56,54,56,78,[90,87,34]],65,478,[6]]
print(ls[3])
print(ls[4])
print(ls[4][3])
print(ls[4][2])
print(ls[4][4][1])

In [ ]:
ls=[23,23,4,45,65,78,[45,34,32,12,[34,56,43,67]],56,78,90,[56]]
print(ls[6])

In [ ]:
ls=[23,23,4,45,65,78,[45,34,32,12,[34,56,43,67]],56,78,90,[56]]
print(ls[6][4])

In [ ]:
ls=[23,23,4,45,65,78,[45,34,32,12,[34,56,43,67]],56,78,90,[56]]
print(ls[6][4])

In [ ]:
ls=[23,23,4,45,65,78,[45,34,32,12,[34,56,43,67]],56,78,90,[56]]
print(ls[6][4][1])

In [ ]:
ls=[23,23,4,45,65,78,[45,34,32,12,[34,56,43,67]],56,78,90,[56]]
print(ls[6][4][3])

In [ ]:
ls=[12,23,34,45,56,67]
print(ls)

In [ ]:
# updation-- Replace the value with a numberor word.

In [ ]:
ls[2]="Hello"
print(ls)

In [ ]:
ls=[12,45,67,89,65,78,90]
print(ls)
ls[4]="SAM"
print(ls)

In [ ]:
# Slice operation
   ":"
ls[3:8] # 3 4 5 6 7--index
ls[:8]  # from the begining---7
ls[3:]  # start from 3 end to the last
ls[:]   # from the begining to last
ls[start:end:step]

In [ ]:
 ls=[12,23,34,45,56,67,78,89,98,87]
print(ls[3:8])
print(ls[:8])
print(ls[3:])
print(ls[:])


In [ ]:
ls=[11,34,45,67,78,98,39,87,76,56]
print(ls[3:])

In [ ]:
ls=[11,34,45,67,78,98,39,87,76,56]
print(ls[2:9])

In [ ]:
ls=[11,34,45,67,78,98,39,87,76,56]
print(ls[:9])

In [ ]:
ls=[11,34,45,67,78,98,39,87,76,56]
print(ls[:])

In [ ]:
ls=[11,34,45,67,78,98,39,87,76,56]
ls[3:7]=["i","hate","you","bro"]
print(ls)

In [ ]:
#Delete an Element from the list 
--------------------------------

del

pop

reomve

In [ ]:


print(ls)
del ls[4]
print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
del ls[3:8]
print(ls)

In [ ]:
# Pop
ls.pop() # Always delete last value 
print(ls)----#Always delete last value 


In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
ls.pop(4)
print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
ls.pop()

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
ls.pop()
print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
del ls[-1:-4:-1]
print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
ls.pop()
print(ls)

In [ ]:
remove()
--------
by this method we can delete the element by providing value to the method.

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
print(ls)
ls.remove(45)
print(ls)

In [ ]:
#List methods
-------------

append()----- it is used to insert an element in the list the element is always inserted at the end of the list

In [ ]:
ls=[12,23,34,45,56,67]
print(ls)
ls.append("hello")
print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78]
print(ls)


In [ ]:
# Make list of 10 integers of your choice

In [ ]:
ls=[]
for i in range (10):
    n=int(input("enter the number"))
    ls.append(n)

print(ls)

In [ ]:
ls=[12,23,34,45,56,67,78,89,98,87]
for i in range(10):
    n=int(input("enter the number"))
    ls.append(n)

print(ls)

In [ ]:
ls_e=[]
ls_o=[]
for i in ls:
    if i%2==0:
        ls_e.append(i)
    else:
        ls_o.append(i)

print("original list",ls)
print("even list",ls_e)
print("odd list",ls_o)


In [ ]:
ls_e=[]
ls_o=[]
for i in ls:
    if i%2==0:
        ls_e.append(i)
    else:
        ls_o.append(i)

print("original lis",ls)
print("even list",ls_e)
print("odd list",ls_o)

In [ ]:
# Max element in the list

In [ ]:
ls=[]
for i in range(5):
    n=int(input("enter the number"))
    ls.append(n)

print("the max element is",max(ls))

In [ ]:
ls=[]
for i in range (6):
    n=int(input("enter the number"))
    ls.append(n)

print("the max element is",max(ls))

In [ ]:
ls=[]
for i in range(3):
    n=int(input("enter the number"))
    ls.append(n)

print("the max element is",max(ls))

In [ ]:
ls=[]
for i in range(2):
    n=int(input("enter the number"))
    ls.append(n)

print("the max element is",max(ls))

In [ ]:
ls=[]
for i in range(2):
    n=int(input("enter the number"))
    ls.append(n)

print("the max element is",max(ls))

In [ ]:
big=ls[0]
for i in ls:
    if i>big:
        big=i
print(ls)
print(big)

In [ ]:
# Extend
--------

It is used to insert more than one element in the list at a time.
Element are always inserted at the end of the list,


In [ ]:
ls=[12,23,34,45,56]
print(ls)
ls.extend([67,78,87])
print(ls)

In [ ]:
a=[1,2,3,4]
b=[2,5,7,8]
print(a+b)

In [ ]:
a=[1,2,3,4]
b=[2,5,7,8]
print(a+b)

a.extend(b)
print(a)

In [ ]:
inset() 

In [ ]:
insert is element in the list at desired index 

ls.insert (index,element)

In [ ]:
ls=[12,23,34,45,56]
print(ls)
ls.insert(3,"Hello")
print(ls)

In [ ]:
copy()

In [ ]:
x=[12,23,34,45]
y=x
print(x)
print(y)
y[2]="satyam"
print(x)
print(y)

In [ ]:
x=[12,23,34,45]
y=x
print(id(x))
print(id(y))
y[2]="satyam"
print(x)
print(y)

In [ ]:
x=[12,23,34,45]
y=x.copy()
print(id(x))
print(id(y))

In [ ]:
x=[12,23,34,45]
y=x.copy()
print(id(x))
print(id(y))
x[3]="SAM"
print(x)
print(y)

In [ ]:
the list can alsom copied using=operator, which points to the same onject as the original. so if any changes is made in the copied list will also reflect in the original dictonary.

In [ ]:
#clear ()

return empty list 

In [ ]:
ls=[12,23,34,45]
print(ls)
ls.clear()
print(ls)

In [ ]:
count()

it returns the frequency of the elemnet in the list

In [ ]:
ls=[12,23,34,45,56,67,23,34,45]
print(ls)
x=ls.count(23)
print(x)

In [ ]:
ls=[12,23,34,45,56,67,23,34,45]
print(ls)
ls1=[]
for i in ls:  (i=insert)
    if i not in ls1:
        ls1.append(i)

print(ls)
print(ls1)

In [ ]:
ls=[12,23,34,45,56,67,23,34,45]
print(ls)
ls1=[]  
for i in ls:    
    if i not in ls1:
        ls1.append(i)

print(ls)
print(ls1)

for i in ls1:
    print(i,"is repeated for",ls.count(i),"times")

In [ ]:
ls=[12,23,34,45,56,67,23,34,45]
print(ls)
ls1=list(set(ls))
print(ls1)


In [ ]:
index ()

- it returns the index of first occurrence of the element in the list.


In [ ]:
ls=[12,23,34,45,34]
print(ls)
x=ls.index(23)
print(x)

In [ ]:
ls=[12,23,34,45,34]
for i in ls:
    x=ls.count(i)
    if x>0:
        print(ls.index(i))

In [ ]:
# sort

arrange the element of ascending or descending order 

In [ ]:
ls=[12,23,21,34,23,56,45,67,65]
print(ls)
ls.sort()
print(ls)

In [ ]:
ls=[12,23,21,34,23,56,45,67,65]
print(ls)
ls.sort(reverse=True)
print(ls)

In [ ]:
# reverse 

it prints the list in reverse order 

In [ ]:
ls=[12,23,21,34,23,56,45,67,65]
print(ls)
ls.reverse()
print(ls)

In [ ]:
ls=[12,23,21,34,23,56,45,67,65]
print(ls)
ls.reverse()
print(ls[: :-1])

In [ ]:
L=["Amit","supriya","satyam","golu"]
print(L*2)

In [ ]:
L=[0.5*x for x in range (4)]
print(L)

In [ ]:
L=['a'*x for x in range(4)]
print(L)

In [ ]:
L=[1*x for x in range(10,1,-4)]
print(L)

In [ ]:
T=[1,2,3,4]
T1=[5,6,7]
L=T.append(T1)
print(L)

In [ ]:
L=[1,5,9]
print(sum(L)+max(L)-min(L))

In [ ]:
 ls=[12,23,34,45,56,[56,54,43,56],43,32,11,[45]]
print(ls[2])

In [ ]:
 ls=[12,23,34,45,56,[56,54,43,56],43,32,11,[45]]
print(ls[3])
ls.insert(4,"Hello")
print(ls)

In [ ]:
 ls=[12,23,34,45,56,[56,54,43,56],43,32,11,[45]]
print(ls[5])
print(ls[5][3])
print(ls[5][2])

In [ ]:
i=1
se=0
so=0
while i<=100:
    if i%2==0:
        se=se+i
    else:
        so=so+i
    i=i+1

print("the sum of even numbers",se)
print("the sum of odd numbers",so)

Python - String
In Python, string is an immutable sequence data type. It is the sequence of Unicode characters wrapped inside single, double, or triple quotes.

'This is a string in Python' # string in single quotes
"This is a string in Python" # string in double quotes
'''This is a string in Python''' # string in triple quotes
"""This is a string in Python""" # string in triple double-quotes

The string is an immutable object. Hence, it is not possible to modify it. The attempt to assign different characters at a certain index results in errors.

immutable - we cannot change in string a particular word.(Alpha numerical code)

In [ ]:
str1='This is the string python'
print(str1)

In [ ]:
str2="This is the string python"
print(str2)

In [ ]:
str3='''this is 
the first 
multi-line string'''
print(str3)

In [ ]:
str2="""this is 
the first 
multi-line string"""
print(str2)

A sequence is defined as an ordered collection of items. Hence, a string is an ordered collection of characters. The sequence uses an index, starting with zero to fetch a certain item (a character in case of a string) from it.

In [ ]:
greet='hello'
print(greet[0])
print(greet[1])
print(greet[2])
print(greet[3])
print(greet[4])
print(greet[5])


In [ ]:
greet='hello'
print(greet[-5])
print(greet[-4])
print(greet[-3])
print(greet[-2])
print(greet[-1])
print(greet[-0])


The string is an immutable object. Hence, it is not possible to modify it. The attempt to assign different characters at a certain index results in errors.

In [ ]:
This program is for "error" the below

In [ ]:
greet='hello'
print(greet)

In [ ]:
greet="hallo"
greet="a"
print(greet)

In [ ]:
greet='hello'
greet[0]='A'
print(greet)

In [ ]:
str()
s=str(100)
print(type(s))

In [ ]:
s=str(-10)
print(s)

In [ ]:
s=str(True)
print(s)

Python capitalize() Method
The capitalize() method returns the copy of the string with its first character capitalized and the rest of the letters lowercased.


Syntax:
string.capitalize()


it won't change orignal it just only modify the frist letter of sentence rest of the letters is lowercased

In [ ]:
b='by delhi'
print('New string:',b.capitalize())

In [ ]:
c='love you bhai'
print('New string:',c.capitalize())

In [ ]:
a='hello world'
print('New string:',a.capitalize())

In [ ]:
a='hello world'
print('New string:',a.capitalize())

Python String count() Method
The count() method searches (case-sensitive) the specified substring in the given string and returns an integer indicating occurrences of the substring. By default, the counting begins from 0 index till the end of the string.


it's a case-sensitive means if we search small so it will only run small 
same as if we run capital letter 


Syntax = mystr=('')
        
        
        total=mystr.count(''0


In [ ]:
mystr='My brother is the best broter in the world'
total=mystr.count('brother')
print('Number of occurance of"brother":',total)

In [ ]:
mystr='i love my family'
total=mystr.count('family')
print('Number of occurance of"family":',total)

In [ ]:
mystr='Madrid is the best software for data scince and learning'
total=mystr.count('Madrid')
print('Number of occurrences of "Madrid":',total)

In [ ]:
mystr='Madrid is the best software for data scince and learning'
total=mystr.count('Madrid')
print('Number of occurrences of "madrid":',total)

Python String endswith() Method
The endswith() function returns True if a string ends with the specified suffix (case-sensitive), otherwise returns False.

In [ ]:
True = voliane   (Value)
False = voliane

In [ ]:
mystr='i hate you'
print(mystr.endswith('you'))
print(mystr.endswith('i'))

In [ ]:
mystr='Pythone is programming language'
print(mystr.endswith('.'))
print(mystr.endswith('age.'))
print(mystr.endswith('language.'))
print(mystr.endswith('programming language.'))
print(mystr.endswith('age'))
                

Python String find() Method
The find() method returns the index of the first occurence of a substring in the given string (case-sensitive). If the substring is not found it returns -1.

In [ ]:
greet='Satya Singh'
print("Index of 'S':",greet.find('S'))
print("Index of 'A':",greet.find('A'))

In [ ]:
greet='Hello world'
print("Index of 'H':",greet.find('H'))
print("Index of 'h':",greet.find('h'))
print("Index of 'e:",greet.find('e'))
print("Index of 'World':",greet.find('World'))

Python String index() Method
The index() method returns the index of the first occurence of a substring in the given string. It is same as the find() method except that if a substring is not found, then it raises an exception.

In [ ]:
there is differnce b/w Index & Find 
find means -1
Index means nothing

In [ ]:
greet='Hello world'
print('Index of 'H':',greet.index('H'))
print('Index of 'e':',greet.index('e'))
print('Index of 'l:',greet.index('l'))
print('Index of 'World':',greet.index('World'))

Python String isalnum() Method
The isalnum() method returns True if all characters in the string are alphanumeric (either alphabets or numbers). If not, it returns False.

Syntax:
str.isalnum()

space & special symbols are not allowed in this program

In [ ]:
mystr='Hello123'
print(mystr.isalnum())

In [ ]:
mystr='12345'
print(mystr.isalnum())

In [ ]:
mystr='Madrid'
print(mystr.isalnum())

In [ ]:
mystr='Python is a programming language.'
print(mystr.isalnum())

In [ ]:
mystr='#1'
print(mystr.isalnum())

Python String isdigit() Method
The isdigit() method returns True if all characters in a string are digits or Unicode char of a digit. If not, it returns False.


str.isdigit()

In [ ]:
mystr='#1'
print(mystr.isdigit())

In [ ]:
mystr='12345'
print(mystr.isalnum())

In [ ]:
mystr='Sam'
print(mystr.isalnum())

In [ ]:
mystr='10.5'
print(mystr.isalnum())

Python String islower() Method
-------------------------------
The islower() method checks whether all the characters of a given string are lowercased or not. It returns True if all characters are lowercased and False even if one character is uppercase.

It returns False if a string contains only symbols and numbers, but returns True if symbols or numbers are with lower case string.

Syntax:
str.islower()

In [ ]:
mystr='hello world'
mystr.islower()

In [ ]:
mystr='Hello.world'
mystr.islower()

Python String istitle() Method
The istitle() method checks whether each word's first character is upper case and the rest are in lower case or not. It returns True if a string is titlecased; otherwise, it returns False. The symbols and numbers are ignored.

str.istitle()

every first word in your sentence will be capitale

In [ ]:
greet='Hello World'
greet.istitle()

 Python String isupper() Method
The isupper() method checks whether all the characters of a given string are uppercase or not. It returns True if all characters are uppercase and False even if one character is not in uppercase.

Symblos and numbers are not affected by this function

Syntax:
str.isupper()



In [ ]:
mystr='HELLO WORLD'
mystr.isupper()

In [ ]:
mystr='hello world'
mystr.isupper()

Python String lower() Method
The lower() method returns the copy of the original string wherein all the characters are converted to lowercase. If no uppercase characters present, it returns the original string. Symbols and numbers remain unaffected by this function.

Syntax:
str.lower()

In [ ]:
mystr = 'HELLO WORLD'
print(mystr.lower())

In [ ]:
mystr = 'ABC123'
print(mystr.lower())

Python String lstrip() Method
The lstrip() method returns a copy of the string by removing leading characters specified as an argument. By default, it removes leading whitespaces if no argument passed.

Leading characters occur at the start of the string (leftmost part of the string).

Syntax:
str.lstrip(characters)

In [ ]:
mystr='     Hello World    '
print(mystr)
print(mystr.lstrip())

Python string.rstrip()
The rstrip() method returns a copy of the string by removing the trailing characters specified as argument. If the characters argument is not provided, all trailing whitespaces are removed from the string.

Trailing characters are those characters which occur at the end of the string (rightmost part of the string).

Syntax:
str.rstrip(characters)

In [ ]:
sl="150gm"
sl.strip("gm")

Python String partition() Method
The partition() method splits the string at the first occurrence of the specified string separator sep argument and returns a tuple containing three elements, the part before the separator, the separator itself, and the part after the separator.

If the matching separator is not found in the string then returns a tuple containing three elements, the string itself as a first element and two empty string elements.

Syntax:
str.partition(sep)

#it returs Tupple 

In [ ]:
mystr=  'Hello World'
print(mystr.partition(' '))

In [ ]:
mystr=  'How are you'
print(mystr.partition('are'))


In [ ]:
mystr=  'tutorials is the best tutorials website'
print(mystr.partition('tutorials'))
print(mystr.partition('Tutorials'))

Python String split() Method
The split() method splits the string from the specified separator and returns a list object with string elements. The default separator is any whitespace character such as space, \t, \n, etc.

Syntax:
str.split(separator)

#it breaks and returs list

In [ ]:
langs='C,Python,R,Java,SQL,Hadoop'
print(langs.split(','))

In [ ]:
langs='C,Pythone,R,Java,SQL,Hadoop'
print(langs.split(',',3))

Python String upper() Method
The upper() method returns a string in the upper case. Symbols and numbers remain unaffected.

The main difference between the capitalize() and the upper() method is that the capitalize() method will capitalize only the first character of the string, whereas the upper() will convert all characters in the upper case.

In [ ]:
mystr="""Hello
        World"""
print(mystr)

In [ ]:
mystr=('Happy'
       'Monday'
       'Everyone')
print(mystr)

#String concatenation

In [ ]:
s1="Hey"
s2="Sam"
s3=s1+s2
print(s3)

In [ ]:
s1="By"
s2="Sam"
s3=s1 + " " + s2
print(s3)

Iterating throungh a String

In [ ]:
# Iterating 
for i in mystr:
    print(i)
    

String Membership

In [ ]:
mystr1= "Hello Everyone"
print('Hello' in mystr1)
print('Everyone' in mystr1)
print('Hi' in mystr1)

Rpartition = is divided from a certain point and make a new sentence.

In [ ]:
str3= "Hello everyone i am doing great How about you"
L= str3.rpartition("How")
print(L)

String Functions

In [ ]:
mystr2= "   Hello Everyone   "
mystr2

In [ ]:
mystr2="********Hello Everyone********Best of luck*******"
mystr2

In [ ]:
mystr2.strip('*')-----It removes all characters from begining & end of the string

In [ ]:
mystr2.rstrip('*')------Removes all '*' characters at the end of the string

In [ ]:
mystr2.lstrip('*')-----Removes all ('*') characters at the beginging of the string

In [ ]:
mystr2="@@@@@***Hello Everyone@@@@@By Everyone****"
mystr2

In [ ]:
mystr2.rstrip('*')

In [ ]:
mystr2.lstrip('*')

In [ ]:
mystr2.lower()

In [ ]:
mystr2 = """Hello Everyone  """

mystr2.lower()-----Return whole string in lower case

In [ ]:
mystr2.upper()----Return whole string in uppercase

In [ ]:
mystr2.replace("He","Ho")----Replace substring "He" with "Ho"

In [ ]:
mystr2.replace(" ","")-----Remove all whitspaces using replace function

In [ ]:
mystr5="one two Three one two three"

In [ ]:
mystr5.count("one")-----Number of times substring"one" occured in string.

In [ ]:
mystr5.startswith("one")-----Return boolean value True if string starts with "one"

In [ ]:
mystr5.endswith("three")----Return boolean value False if string ends with "three"

Split--- Returns list

In [ ]:
# Combining string & numbers using format method 
item1=40
item2=60
item3=70
"cost of item1,item 2 and item3 are{},{} and {}"
print("cost of item1,item 2 and item3 are{},{} and {}")

In [ ]:
# Combining string & numbers using format method 
item1=30
item2=34
item3=45

res="cost of item3,item2 and item1 are {2},{1} and{0}"
print(res.format(item1,item2,item3))

In [ ]:
item1=34
item2=34
item3=78
print("cost of item1,item 2 and item3 are{},{} and {}".format(item1,item2,item3))

In [ ]:
str2= " WELCOME EVERYONE "
str2=str2.center(100)
print(str2)

In [ ]:
str2= " WELCOME EVERYONE "
str2=str2.center(100,'*')----# Center align the string using a specific character
print(str2)

In [ ]:
str2= " WELCOME EVERYONE "
str2=str2.rjust(50)-----# Right align the string using a specific character as the 
print(str2)

In [ ]:
str2= "one two three four five six"
loc=str2.find("four")---# Find the location of word 'four' in the string"str2"
print(loc)

In [ ]:
mystr6='123456789'
print(mystr6.isalnum())--Rturns true if a string contains only letters or numbers
print(mystr6.isdecimal())--Returns true if all the characters are decimals(0-9)
print(mystr6.isnumeric())---Returns true if all the characters are numeric(0-9)
print(mystr6.isalpha())---Returns true if all the characters in the text are letters

In [ ]:
New chapter--Tuple

sequence data structure
enclosed in()
indexed,orderd
"immutable"-----can not be change once created 


In [ ]:
qns:- What is the differnce between list and tuple
ans:- list is mutable and tuple is immutable

Immutable---can not be change once created.

syntax---t1=(1,2)

In [ ]:
t1=(12,23,34,45,56)--Tuple of integers
t1=("How","are","you")
t1=((1,2),(2,3))

In [ ]:
Tuple constructor
-----------------
t1=tuple("sam")
te

In [ ]:
t1=12,23,34,45,56---Tuple packing

a,b,c,d,e=t1----Tuple unpacking
print(a)
print(b)
print(c)
print(d)
print(e)

In [ ]:
t1=12,23,34,45,56

a,b,c,d,e=t1
print(a)
print(b)
print(c)
print(d)
print(e)

t1=(12)----We cannot code with sigle value if we cannot use (,) for proving it's tuple--perhaps the value will come in integers
print(type(t1))

In [ ]:
Accessing

In [ ]:
t1=(12,23,34,45,56,67)
print(t1[0])
print(t1[3])
print(t1[-1])
print(t1[-2])

In [ ]:
Updating

In [ ]:
t1=(12,34,34,44)
t2=("how","are","you")
print(t1+t2)

In [ ]:
Index() method

In [ ]:
t1=(12,23,34,45,56,67)
print(t1)
x=t1.index(45)
print(x)

In [ ]:
t1=(12,23,34,45,56)
print(t1)
x=t1.index(56)
print(x)

In [ ]:
Updating an element in tuple 

In [ ]:
t1=(1,23,34,56,6,7)
ls=list(t1)
ls.append(89)----Is use for adding elements in Tuple,Integers<list
t1=tuple(ls)
print(t1)

In [ ]:
t1=(1,23,4,5,67,88)
ls=list(t1)
ls.append(78)
t1=tuple(ls)
print(t1)

In [ ]:
Update an element in the tuple

In [ ]:
t1=(1,2,34,5,6,7,8)
ls=list(t1)
ls[3]="hello"
t1=tuple(ls)
print(t1)

In [ ]:
t1=(1,2,3,4,6,7,78)
ls=list(t1)
ls[3]="sam"
t1=tuple(ls)
print(t1)

In [ ]:
Tuple 
1.Tuple is similar to List expect that the object in tuple are the immutable which means we cannot change the elements of tuple once assigned.
2.When we do want to change data over time. tuple is preferred data type
3.Iterating over the elements of tuple is faster compared to iterating over the list

In [ ]:
tup1=()--Empty tuple
tup2=(10,20,30)---tuple of integers number
tup3=(10.77,30.66,60.89)---tuple of float numbers
tup4=('one','two',"three")----tuple of strings
tup5=('Asif'.25,(50,100),(150,90))---Nested tuple
tup6=(100,'Asif',17.765)---tuple of mixed data types


In [ ]:
Sorting

In [ ]:
mytuple2=(23,7,15,56,67,89)
sorted(mytuple2)---Returns a new sorted list and doesn't change orignal tuple

In [ ]:
mytuple2=(23,7,15,56,67,89)
sorted(mytuple2,reverse=True)---Sort in descending order 


DICTIONARY-----NEW CHAPTER

python-Dictionary
The dictionary is an unorderd collection that contains key:value pairs separated by commas inside curly brackets.Dictionary are optimuzed to retrieve value when the key is known.

In [ ]:
The following declars a dictionary object.

capitals={"USA":"Washington D.C","France":"Paris","India":"New Delhi"}
print(type(capitals))

In [ ]:
capitals={"USA":"Washington D.C","France":"Paris","India":"New Delhi"}
print(type(capitals))

d={} # empty dictionary

numNames={1:"One",2:"Two",3:"Three",4:"Four"}---int key, string value

decNames={1.5:"One and Half",2.5:"Two and Half",3.5:"Three and Half")---float key,string value

item={("Parker","Reynolds","Calmin"):"pen",("LG","Whirlpool","Samsung"):"Refrigerator"}---tuple key, string value

romanNums={'I':1,

The same key cannot appear more than once in a collection.If the key appears more than once,only the latest will be retained. The value can be of any data type. One value can be assigned to more than aone key.

In [ ]:
numNames={1:"One",2:"Two",3:"Three",2:"two",1:"one"}
print(numNames)

In [ ]:
A dictionary can also be created using the dict() constructor methor

In [ ]:
emptydict=dict()
print(emptydict)

In [ ]:
numdict=dict(I="one",II="Two",III="Three")
print(numdict)

In [ ]:
numdict=dict([('I','one'),('II','two'),('III','Three')])
print(numdict)

In [ ]:
d1={"Name":"Nimrit","Age":45,"City":"Delhi"}
print(d1)

print(d1["City"])

In [ ]:
d1={"Name":"Nimrit","Age":45,"City":"Delhi"}
print(d1)
print(d1["City"])
print(d1.get("Sam"))

In [ ]:
capitals={"USA":"Washington D.C","France":"Paris","India":"New Delhi"}
print(capitals["USA"],capitals["France"],)



In [ ]:
capitals={"USA":"Washington D.C","France":"Paris","India":"New Delhi"}
print(capitals["USA"],capitals["France"],)
print(capitals["usa"])

Use the get() method to retrieve the key's value even if keys are not known. It returns None if the key does not exist instead of raising an error.

In [ ]:
numNames={1:"One",2:"Two",3:"Three"}
print(numNames.get(1),numNames.get(2),numNames.get(5))

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
for i in d1:
    print(i)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
for i in d1.values():
    print(i)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
for i in d1:
    print("key=",i,"value=",d1[i])

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
for i,j in d1.items():
    print(i,j)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
d1.items()

In [ ]:
Access Dictionary using loop
use for thr loop to iterate a dictionary in python script.


In [ ]:
capitals={"USA":"Washington D.C","France":"Paris","India":"New Delhi"}
for key in capitals:
    print(" key = " + key +  " value = " +capitals[key])

Update Dictionary
As mentioned earlier, the key cannot appear more than once. Use the same key and assign a new value to it to update the dictionary object.

In [ ]:
captains={"England":"Root","Australia":"Smith","India":"Dhoni"}
print(captains)

Deleting Values from a Dictionary
Use the del keyword, pop(), or popitem() methods to delete a pair from a dictionary or the dictionary object itself. To delete a pair, use its key as a parameter. To delete a dictionary object itself, use del dictionary_name.

In [ ]:
captains={'Australia':'Paine','India':'Virat','Srilanka':'Jayasurya'}
print(captains)

In [ ]:
captains={'Australia':'Paine','India':'Virat','Srilanka':'Jayasurya'}
print(captains)
del captains['Australia']---delete a key-value pair 
print(captains)

In [ ]:
captains={'Australia':'Paine','India':'Virat','Srilanka':'Jayasurya'}
print(captains)
del captains-----delete dict object
print(captains)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
del d1['b']
print(d1)
print(d1.pop('c'))
print(d1)
print(d1.popitem())
print(d1)


In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
del d1['b']
print(d1)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
print(d1.pop('c'))
print(d1)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
print(d1.popitem())
print(d1)

In [ ]:
Multi-dimension Dictionary
Let's assume there are three dictionary objects, as below:

In [ ]:
d1={"Name":"Satyam","Age":23,"Marks":60}
d2={"Name":"Sat","Age":22,"Marks":78}
d3={"Name":"ruh","Age":21,"Marks":23}
students={1:d1,2:d2,3:d3}
print(students)
print(students[1])
print(students[2])
print(students[3])

Python Dictionary clear()
The dict.clear() methor removes all the key-value pairs from the dictionary.

In [ ]:
romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
print("Dictionary:",romanNums)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
d2=d1
print(d1)
print(d2)
d1.clear()
print(d1)
print(d2)

In [ ]:
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
d2=d1.copy()
print(d1)
print(d2)
d1.clear()
print(d1)
print(d2)

Python Dictionary copy()
The dict.copy() method returns a shallow copy of the dictionary.

The dictionary can also be copied using the = operator, which points to the same object as the original. So if any change is made in the copied dictionary will also reflect in the original dictionary.

Syntax:
dict.copy()

In [ ]:
romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
newRomanNums=romanNums.copy()
print("original dictionary:",romanNums)
print("Copied dictionary:",newRomanNums)

Python Dictionary fromkeys()
The dict.fromkeys() method creates a new dictionary from the given iterable (string, list, set, tuple) as keys and with the specified value.

Syntax:
dictionary.fromkeys(sequence, value)

In [ ]:
keys={'Mumbai','Bangalore','Chicago','New York'}
value='city'
dictionary=dict.fromkeys(keys,value)
print(dictionary)

In [ ]:
keys={'Mumbai','Bangalore','Chicago','New York'}
dictionary=dict.fromkeys(keys,)
print(dictionary)

Python Dictionary items()
The dict.items() returns a dictionary view object that provides a dynamic view of dictionary elements as a list of key-value pairs. This view object changes when the dictionary changes.

Syntax:
dict.items()

In [ ]:
romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
dictview=romanNums.items()
print(dictview)

romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
keysPython Dictionary popitem() Method
The dict.popitem() method removes and returns a tuple of (key, value) pair from the dictionary. Pairs are returned in Last In First Out (LIFO) order.

Syntax:
dict.popitem()=romanNums.keys()
print(keys)Python Dictionary popitem() Method
The dict.popitem() method removes and returns a tuple of (key, value) pair from the dictionary. Pairs are returned in Last In First Out (LIFO) order.

Syntax:
dict.popitem()

Python Dictionary pop()
The dict.pop() method removes the key and returns its value. If a key does not exist in the dictionary, then returns the default value if specified, else throws a KeyError.

Syntax:
dict.pop(key, default)

In [ ]:
x={'I':1,'II':2,'III':3,'IV':4,'V':5}
print("Dictionary:",x)

y={'I':1,'II':2,'III':3,'IV':4,'V':5}
x.update(y)
print("Update  Dictionary:",x)

#### 

Python Dictionary values()
The dict.values() method returns the dictionary view object that provides a dynamic view of all the values in the dictionary. This view object changes when the dictionary changes.

Syntax:
dict.values()

In [67]:
romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
values=romanNums.values()
print(values)

dict_values([1, 2, 3, 4, 5])


In [ ]:
romanNums={'I':1,'II':2,'III':3,'IV':4,'V':5}
kesy=romanNums.keys()
print(keys)

In [ ]:
mydict1=('DOB':2001)
mydict1

In [ ]:
mydict1={'Name':'Asif','ID':'1234','DOB':'2001','Job':'Analyst'}
mydict1
'Name' is in mydict1-----(True)---Test if a key is in a dictionary or not
'Asif' is in mydict1----(False)----Membership test can be only done for keys.

In [ ]:
mydict1={'Name':'Asif','ID':'1234','DOB':'2001','Job':'Analyst'}
mydict1
('Name','ID') is in mydict1


In [ ]:
mydict1={'Name':'Asif','ID':'1234','DOB':'2001','Job':'Analyst'}
mydict1
all(mydict1)------Will Return false as the value is false (value 0)

In [ ]:
mydict1[1]='test1'
mydict1
all(mydict1)

In [ ]:
mydict1[1]='test1'
mydict1


In [ ]:
double={i:i*2 for i in range(10)}
double

In [ ]:
square={i:i*5 for i in range(20)}
square

In [ ]:
key=['one','two','three','four','five']
value=[1,2,3,4,5]

mydict={k:v for (k,v) in zip(key,value)}
mydict


In [9]:
mydict1={'a':10,'b':20,'c':30,'d':40,'e':50}
mydict1={k:v/10 for (k,v) in mydict1.items()}----Divide all values in dictionary
mydict1

{'a': 1.0, 'b': 2.0, 'c': 3.0, 'd': 4.0, 'e': 5.0}

In [ ]:
str1="abcdefghijklmnopqrstuvwxyz"
mydict3={i:i.upper() for i in str1}---- Lower to upper case
mydict3

In [ ]:
Fumctions
. A function is a block of organized code written to carry out

In [ ]:
Parameter VS Argument 
- A parameter is the variable listed inside the parentheses in the function definition.---(a,b)
- An argument is the value that is sent to the function when it is called.---s(10,20)

In [ ]:
Three types of functions in python
1. Built-in funtion:- Python predefined functions that are readily availabe for use like min(),max(),sum(),print()etc.
2. User-Defined functions:- Function that we define ourselves to perform 

Default Function
Argument 
Return Type
Placeholder
Args,kwargs

syntax---def function_name():


In [1]:
def function_name():-----Function_defination
    logic

In [ ]:
function_name()-----Calling

In [63]:
def addition():
    a=int(input("enter the number"))
    b=int(input("enter the number"))
    c=a+b
    print("the sume is",c)

addition()
addition()



enter the number 67
enter the number 54


the sume is 121


enter the number 56
enter the number 43


the sume is 99


In [65]:
def interest():
    p=int(input("enter the number"))
    r=int(input("enter the number"))
    t=int(input("enter the number"))
    si=p*r*t/100
    print("the intrerest is",si)

interest()
interest()

enter the number 56
enter the number 54
enter the number 43


the intrerest is 1300.32


enter the number 56
enter the number 54
enter the number 56


the intrerest is 1693.44


In [ ]:
def check():
    n=int(input("enter the number"))
    if n%2==0:
        print("Even number")
    else:
        print("Odd number")

check()

In [ ]:
def year():
    n=int(input("enter the number" ))  
    if year%4==0:
    print("leap year")
else:
    print("non leap year")

year()

In [ ]:
def fectorial():
    n=int(input("enter the number"))
    f=1
    for i in range(1,n+1):
        f=f*i
        print("the fectorial is",f)

factorial()

In [ ]:
def reverse():
    n=int(input("enter the number"))
    rev=0
    while n>0:
        rev=rev*10+n%10
        n=n//10
    print("the reverse is",rev)



reverse()
    

Argument function
-----------------

def function_name(arg1,arg2....):
    logic

function_name(arg1.arg2...)

In [178]:
def addition(a,b):
    c=a+b
    print("the sum is",c)

addition(56,65)
         

the sum is 121


In [1]:
def year():
    year=int(input("enter the year"))
    if year%4==0:
        print("leap year")
    else:
        print("non leap year")

year()


enter the year 6765


non leap year


In [17]:
def fectorial():
    n=int(input("enter the number"))
    f=1
    for i in range(1,n+1):
        f=f*i
        print("the fectorial is",f)

fectorial()

enter the number 3


the fectorial is 1
the fectorial is 2
the fectorial is 6


In [21]:
def reverse():
    n=int(input("enter the number"))
    rev=0
    while n>0:
        rev=rev*10+n%10
        n=n//10
        print("the reverse is",rev)

reverse()

enter the number 67


the reverse is 7
the reverse is 76


In [27]:
def fectorial():
    n=int(input("enter the number"))
    f=1
    for i in range(1,n+1):
        f=f*i
        print("the fectorial is",f)

fectorial()

enter the number 5


the fectorial is 1
the fectorial is 2
the fectorial is 6
the fectorial is 24
the fectorial is 120


In [59]:
def reverse():
    n=int(input("enter the number"))
    rev=0
    while n>0:
        rev=rev*10+n%10
        n=n//10
        print("the reverse is",rev)

reverse()

enter the number 6


the reverse is 6


In [37]:
def check():
    n=int(input("enter the number"))
    if n%2==0:
        print("even number")
    else:
        print("odd number")

check()
    

enter the number 56


even number


In [41]:
def check():
    n=int(input("enter the number"))
    if n%2==0:
        print("even number")
    else:
        print("odd number")

check()

enter the number 33


odd number


In [43]:
def interest():
    p=int(input("enter the number"))
    r=int(input("enter the number"))
    t=int(input("enter the number"))
    s=p*r*t/100
    print("the interest is",s)

interest()

enter the number 32
enter the number 32
enter the number 21


the interest is 215.04


In [57]:
def revers():
    n=int(input("enter the number"))
    rev=0
    while n>0:
        rev=rev*10+n%10
        n=n//10
        print("the revers is",rev)

revers()

enter the number 6


the revers is 6


In [61]:
def fectorial():
    n=int(input("enter the number"))
    f=1
    for i in range(1,n+1):
        f=f*i
        print("the fectorial is",f)

fectorial()

enter the number 32


the fectorial is 1
the fectorial is 2
the fectorial is 6
the fectorial is 24
the fectorial is 120
the fectorial is 720
the fectorial is 5040
the fectorial is 40320
the fectorial is 362880
the fectorial is 3628800
the fectorial is 39916800
the fectorial is 479001600
the fectorial is 6227020800
the fectorial is 87178291200
the fectorial is 1307674368000
the fectorial is 20922789888000
the fectorial is 355687428096000
the fectorial is 6402373705728000
the fectorial is 121645100408832000
the fectorial is 2432902008176640000
the fectorial is 51090942171709440000
the fectorial is 1124000727777607680000
the fectorial is 25852016738884976640000
the fectorial is 620448401733239439360000
the fectorial is 15511210043330985984000000
the fectorial is 403291461126605635584000000
the fectorial is 10888869450418352160768000000
the fectorial is 304888344611713860501504000000
the fectorial is 8841761993739701954543616000000
the fectorial is 265252859812191058636308480000000
the fectorial is 822283865417

Return type function 
---------------------

def function_name(arg1,arg2)
logic/statment
return value /value

var=function_name(arg1,arg2)
print(var)

print(function_name(arg1,arg2))

In [14]:
def addition(a,b):
    return a+b
c=addition(32,45)
print(c)

print(addition(45,32))

77
77


In [18]:
x=mathop(23,34)
print(x)

(57, -11, 782, 0.6764705882352942)


In [20]:
s,a,m,d=mathop(21,34)
print("sum",s)
print("sub",a)
print("mul",m)
print("div",d)

sum 55
sub -13
mul 714
div 0.6176470588235294


placeholder argument
--------------------
def addition(a,b=400,c=300):
    return a+b+c

print(addition(200))

In [24]:
def addition(a,b=400,c=300):
    return a+b+c

print(addition(200,300)) placeholder argument 

800


In [28]:
def datascince(a,b,c,d,e):
    return(a+b,a*b)

datascince(1,2,3,4,5)

(3, 2)

In [44]:
def hello(a,b):
    return("my name is {} and gender is {}".format(a,b))
hello("sam",23)

'my name is sam and gender is 23'

In [46]:
def addition(a,b=700,c=600):
    return a+b+c

print(addition(300))
print(addition(a=400,c=500))
print(addition(100,200,300))

1600
1600
600


In [52]:
def hello(name,age=23,gender="male"):
    return("my name is {},and age is {},and gender id {}".format(name,age,gender))\

hello("sam")

'my name is sam,and age is 23,and gender id male'

Format of args,Kwargs,
---------------------
1. unpacking operators are operators that unpack the values from iterable objects in python.
2. The single asterisk operators* can be used on any iterable that python provides.
3. While the dounle astrisk operators** can only used on dictionaries.

In [57]:
u=[1,2,3]
u
print(*u)

1 2 3


In [59]:
u=[1,2,3]
u

[1, 2, 3]

In [61]:
a,*b,c=[1,2,3,4,65,7,8,9]
a

1

In [63]:
a,*b,c=[1,2,3,4,65,7,8,9]
b

[2, 3, 4, 65, 7, 8]

In [67]:
*a,b,c=[1,2,3,4,65,7,8,9]
a

[1, 2, 3, 4, 65, 7]

In [69]:
a=[1,2,3]
b=[4,5,6]
c=[*a,*b]---it removes brackets.
c

[1, 2, 3, 4, 5, 6]

In [71]:
a=[1,2,3]
b=[4,5,6]
c=[a,b]
c

[[1, 2, 3], [4, 5, 6]]

In [73]:
a=[*"realpython"]
a
#b=list("realpython")
#b

['r', 'e', 'a', 'l', 'p', 'y', 't', 'h', 'o', 'n']

In [89]:
d1={'A':1,'B':2}
d2={'C':3,'D':4}
d1.update(d2)
d1

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [93]:
d1={'A':1,'B':2}
d2={'C':3,'D':4}
d3={**d1,**d2}
d3

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [109]:
def my_sum(*a):
    result=0
    for i in a:
        result=result+i
    return result

list1=[1,2,3]
list2=[4,5]
list3=[6,7,8,9]
my_sum(*list1,*list2,*list3)

45

In [111]:
def my_sum(*a):
    result=0
    for i in a:
        result=result+i
    return result

my_sum(34,45,656)

735

___________ZIP FUNCTION__________
1. Zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the secound item each passed iterator are paried together etc.
2. if the passed iterator have different length, the iterator with the least items decides the length of the new iterator.

SYNTAX:- zip(iterator1,iterator2,iterator3.....)

In [114]:
a=["Sam","singh","name"]
b=["Jenny","ashwin"]
list(zip(a,b))

[('Sam', 'Jenny'), ('singh', 'ashwin')]

In [116]:
a="no"
b="yes"
list(zip(a,b))

[('n', 'y'), ('o', 'e')]

In [118]:
number_list=[1,2,3,3]
str_list=['one','five','four',"three"]

result=list(zip(number_list,str_list))
print(result)

[(1, 'one'), (2, 'five'), (3, 'four'), (3, 'three')]


In [120]:
number_list=[1,2,3,3]
str_list=['one','five','four',"three"]

result=list(zip(number_list,str_list))
print(result)

result_set=set(result)
print(result_set)

[(1, 'one'), (2, 'five'), (3, 'four'), (3, 'three')]
{(2, 'five'), (3, 'three'), (1, 'one'), (3, 'four')}


In [136]:
numberlist=[1,2,3]
str_list=['one','two']
number_tuple=('ONE','TWO','THREE','FOUR')

result=zip(numberlist,number_tuple)
print(list(result))

result1=zip(numberlist,str_list,number_tuple)
print(list(result1))

[(1, 'ONE'), (2, 'TWO'), (3, 'THREE')]
[(1, 'one', 'ONE'), (2, 'two', 'TWO')]


ENUMERATED

In [124]:
s1="PYTHON"
list(enumerate(s1))

[(0, 'P'), (1, 'Y'), (2, 'T'), (3, 'H'), (4, 'O'), (5, 'N')]

In [128]:
l1=["DL","ML","NLP"]
ls=list(enumerate(l1))
ls

[(0, 'DL'), (1, 'ML'), (2, 'NLP')]

In [130]:
b=enumerate(s1)
list(a)
list(b)
list(enumerate(l1,100))

[(100, 'DL'), (101, 'ML'), (102, 'NLP')]

In [132]:
l1=["DL","ML","NLP"]
for i,j in enumerate(l1):
    if i<2:
        print(j,i)

DL 0
ML 1


LAMBDA FUNCTION
---------------
It's a annonymous function which doesn't have name.

In [139]:
x=lambda a:a+10----lambda var: expression(annoymous)
x(1000)

1010

In [143]:
def kelvin( a):
    return ( a+10)

kelvin(10)

20

In [147]:
z=lambda a,b,c:a+b+c
z(10,20,30)

60

In [151]:
a=lambda x: x+2
a

<function __main__.<lambda>(x)>

In [155]:
ismail=lambda a,b,c:a+b*c----a+(b+c8d)+f/(a*b)                                          
ismail(7339,838,453)

386953

IF & ELSE CONDITION IN LAMBDA


In [12]:
a=lambda x: x*2 if x%2==0 else x
a(32)

64

MAP FUNCTION 
-------------
SYNTAX
map(fun,iter)

PARAMETERS:-
fun: it is a function to which map passes each element of given iterable.

iter: it is a iterable which is to be mapped.

There is 2 types of function in LAMBDA
--------------------------------------
1. map it is use for changes is existing list
1. filter is use for extract in list

In [32]:
number=[1,2,3,4]
list(map(lambda x: x+x,[1,2,3,6]))

[2, 4, 6, 12]

In [36]:
def addition(n):
    return(n*2)

number=[12,23,44,56]
list(map(addition,number))-------List (map(lambda x:x*2,number))

[24, 46, 88, 112]

In [14]:
numbers1=[1,2,3,4]
numbers2=[5,6,7]
numbers3=[3,4,2,1]
result=(map(lambda x,y,z:x+y+z,numbers1,numbers2,numbers3))
list(result)

[9, 12, 12]

In [54]:
numbers1=[1,2,3]
numbers2=[4,5,6]
numbers3=[1,3,4]
result=(map(lambda x,y,z:x+y+z,numbers1,numbers2,numbers3))
list(result)

[6, 10, 13]

In [58]:
my_pets=['bruu','tommy','jack']
list(map(lambda x: x.upper(),my_pets))

['BRUU', 'TOMMY', 'JACK']

In [62]:
my_strings=['a','b','c','d','e']
my_numbers=[1,2,3,4,5]
my_name=['xx','yy','zz','ww','dd']
results=list(map(lambda x,y,z:(y,x+z),my_strings,my_numbers,my_name))
list(results)

[(1, 'axx'), (2, 'byy'), (3, 'czz'), (4, 'dww'), (5, 'edd')]

FILTER
------
It extracts even and odd number.
filter() method returns an iterator that passed the function check for each element in the iterable.

In [72]:
dromes=("demigod","rewire","god","freer","auntgshdjkshd","sasa")
palindromes=list(filter(lambda g:g == g[::-1],dromes))
palindromes

[]

In [74]:
a="ankush"
a[::-1]

'hsukna'

In [78]:
my_list=[1,2,3,5,6,4,8,12]
new_list=list(filter(lambda x:(x%2==0),my_list))
print(new_list)



[2, 6, 4, 8, 12]


In [80]:
li=[5,3,33,22,54,67,54,89]
final_list=list(filter(lambda x:(x%2!=0),li))
print(final_list)

[5, 3, 33, 67, 89]


In [88]:
list2=['ONE','TWO','THREE','FOUR']
upper=list(filter(lambda x: x.isupper(),list2))----
lower=list(filter(lambda x: x.islower(),list2))
print(upper)
print(lower)
print('-------')

['ONE', 'TWO', 'THREE', 'FOUR']
[]
-------


In [106]:
list3=['one','two2','three','88','99','102']
numeric=list(filter(lambda x: x.isnumeric(),list3))----filter numeric
alpha=list(filter(lambda x: x.isalpha(),list3))----filter character
alphanum=list(filter(lambda x: x.isalnum(),list3))----filter number&character
print(alpha)
print(numeric)
print(alphanum)
print('------')

['one', 'three']
['88', '99', '102']
['one', 'two2', 'three', '88', '99', '102']
------


In [110]:
doubles=[2,6,10,14,18]
doubles
from functools import reduce
def add(a,b):
    return a+b

sum_all=reduce(add,doubles)--This reduce function will perform sum of all item
sum_all

50

In [112]:
The below reduce()dunction will perform sum of all items in the list in the list using lambda
sum_all=reduce(lambda a,b:a+b,doubles)
sum_all

50

In [5]:
importoperator reduce
from functools import reduce
list2=[1,2,3,4]
product=reduce(operator.mul,list2)
print(product)
add=reduce(operator.add,list2)
print(add)
concat_str=reduce(operator.add,['puthon',' ','Rocks'])
print(concat_str)
prod=reduce(operator.mul,['Hello',3])
print(prod)
min_num=reduce(lambda a,b:a if a<b else b, list2)
print(min_num)
max_num=reduce(lambda a,b:a if a>b else b,list2)
print(max_num)


SyntaxError: invalid syntax (1382570017.py, line 1)

In [136]:
print('----')
print(reduce(lambda a,b:bool(a and b),[0,0,1,0,0]))
print(reduce(lambda a,b:bool(a and b),[2,3,1,5,6]))
print(reduce(lambda a,b:bool(a and b),[8,9,1,0,9]))
print('-----')
print('----')
print(reduce(lambda a,b:bool(a or b),[0,0,0,0,0]))
print(reduce(lambda a,b:bool(a or b),[2,3,1,5,6]))
print(reduce(lambda a,b:bool(a or b),[8,9,1,0,9]))
print('-----')

----
False
True
False
-----
----
False
True
True
-----


In [148]:
import pandas as pd
pd.to_datetime("01-09-2024")


Timestamp('2024-01-09 00:00:00')

In [154]:
pd.to_datetime("09-01-2024").month

9

In [156]:
pd.to_datetime("09-02-2024").day

2

In [158]:
pd.to_datetime("09-02-2024").dayofweek

0

In [162]:
pd.to_datetime("07-07-2001").day_name()

'Saturday'

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

USE for advance math operation

NumPy Ndarray
Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [6]:
a=np.array([1,2.0,3])
print(a)


[1. 2. 3.]


In [8]:
a=np.array([1,'a',3])
print(a)


['1' 'a' '3']


In [10]:
a=np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5],ndmin=9)
print(a)


[[[[[[[[[1 2 3 4 5]]]]]]]]]


In [14]:
a=np.array([1,2,3],dtype=float)
print(a)


[1. 2. 3.]


In [18]:
a=np.array([1,2,3],dtype=complex)
print(a)


[1.+0.j 2.+0.j 3.+0.j]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [39]:
# it defines rows and columns 
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape=(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [21]:
# Numpy also provides a reshape functione to resize an array.
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
# it returns the array with the all zeros
import numpy as np
x=np.zeros((2,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [35]:
# numpy returns a new array of specified size type, filled with ones
# array of five ones. Default dtype is float
import numpy as np
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [37]:
import numpy as np
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [41]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [43]:
a=np.zeros(5,dtype=int)
print(a)
a.ndim

[0 0 0 0 0]


1

In [45]:
a.shape

(5,)

In [47]:
a.size

5

In [49]:
b=np.zeros((2,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
x=2*(np.ones(5))
print(x)

[2. 2. 2. 2. 2.]


In [53]:
y=np.ones((2,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
# Identity matrix --- means diagnol way
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [71]:
import numpy as np
a=np.array([[12,23,34],[23,66,54],[55,43,22]])
print(a)
print(np.diag(a))

[[12 23 34]
 [23 66 54]
 [55 43 22]]
[12 66 22]


In [69]:
x=np.diag([3,4,5,6,7])
print(x)

[[3 0 0 0 0]
 [0 4 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 7]]


In [79]:
matrix2=np.array([[2,3,4,4],[7,7,4,3],[1,2,3,4]])
print("\n3x3 matrix:\n",matrix2)


3x3 matrix:
 [[2 3 4 4]
 [7 7 4 3]
 [1 2 3 4]]


In [81]:
matrix2=np.array([[2,3,4,4],[7,7,4,3]])
print("\n2x2 matrix:\n",matrix2)


2x2 matrix:
 [[2 3 4 4]
 [7 7 4 3]]


In [85]:
matrixa=np.array([[2,3,4,4],[7,7,4,3]])
matrixb=np.array([[2,3,4,1],[7,2,4,3]])
matrixc=matrixa+matrixb
print(matrixc)

[[ 4  6  8  5]
 [14  9  8  6]]


In [93]:
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])
result=np.dot(matrix1,matrix2)
print("matrix1 x matrix2:\n",result)


# 1 3     2 6         1*2+3*4    1*6+3*8
  5 7     4 8     

matrix1 x matrix2:
 [[25 12]
 [63 35]]


In [97]:
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()
result=np.transpose(matrix1)
print(result)

[[1 3]
 [5 7]]

[[1 5]
 [3 7]]


numpy.arange
This function returns an ndarray object containing evenly spaced within a given range.

In [102]:
import numpy as np
a=np.arange(24)
print(a)
a.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

In [104]:
import numpy as np
x=(np.arange(10,22,2)).reshape(2,3)
print(x)
a.ndim

[[10 12 14]
 [16 18 20]]


1

Comparison b/w list and arrays
-------------------------------
Benefits of arrays
1.Takes less memory
2.Fast
3.Convininent


A normal integer is 28 bites


Array take 4 bits

In [107]:
import sys
import time

sys.getsizeof(99)--- Just integer

28

In [117]:
import numpy as np
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [119]:
import numpy as np
a=np.arange(2000000)
print(a.itemsize)
print()

print(a.itemsize*len(a))

4

8000000


In [121]:
a1=range(1000000)
b1=range(1000000)
start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time()-start)*1000)
    

time taken: 250.93340873718262


In [123]:
a1=range(10)
b1=range(10)
list(zip(a1,b1))

[(0, 0),
 (1, 1),
 (2, 2),
 (3, 3),
 (4, 4),
 (5, 5),
 (6, 6),
 (7, 7),
 (8, 8),
 (9, 9)]

In [133]:
import numpy as np
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()
c2=a2+b2
print("time taken by array:",(time.time()-start)*1000)


time taken by array: 0.0


In [135]:
n1=np.arange(100)
n2=np.arange(100)
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [137]:
n2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [153]:
l=[1,"2",3,4,5]
l1=l
l1
l1[2]=100
l1
1
print(id(l1)),print(id(1))

2599153270464
140731914664376


(None, None)

In [155]:
l2=l.copy()
l2[1]=100
1
12
print(id(l),id(l2))

2599153270464 2599153329024


In [159]:
l2[3]=100
l2



[1, 100, 100, 100, 5]